services:
  web:
    build: apache
    hostname: web
    ports:
      - 80:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - a23bernalrc.ddnsfree.com
          - www.a23bernalrc.ddnsfree.com
    volumes:
      - ./app:/app
      - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
      - ./apache/certs:/certs
  basededatos:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: abc123.
      MARIADB_USER: example-user
      MARIADB_PASSWORD: abc123.
      MARIADB_DATABASE: example-database
    volumes:
      - datos:/var/lib/mysql
    networks:
      - rede_test
  phpmyadmin:
    image: phpmyadmin
    networks:
      - rede_test
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=basededatos
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - rede_test
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_test:
volumes:
  datos:
