services:
  ##web1:
  ##  image: httpd
  ##  ports:
  ##    - 8080:80
  ##  volumes:
  ##    - /media/MV-Linux/MaquinasVirtuais/a23bernalrc/Repositorios/TemarioDAW2/Temario/prueba:/prueba
  bd:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=abc123..
    volumes:
