services:
  web1:
    build: debian
    hostname: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
  bd:
    image: mysql
    hostname: basededatos

    env_file:
    - .env_bd
    volumes:
    - datosbd:/var/lib/mysql
    secrets:
    - db_root_password
    - db_password
    phpmyadmin:
    - image: phpmyadmin
    ports:
    - 8000:80
    environment:
      - PMA_HOST=bd
