services:
  web:
    build: apache
    hostname: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf
      # - ./apache/php.ini:/etc/php/8.2/apache2/php.init
      - ./apache/certs:/certificados
    networks:
      rede_test:
        aliases:
          - a23danielgs.ddnsfree.com
          - www.a23danielgs.ddnsfree.com
          - danigs.tech
    env_file:
      - .env_dev
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - rede_test
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress
      MARIADB_USER: danielgs
      MARIADB_PASSWORD: abc123.
    volumes:
      - datos:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - rede_test
  # adminer:
  # image: adminer
  # restart: always
  # ports:
  #   - 8081:8080
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    networks:
      - rede_test

networks:
  rede_test:

volumes:
  datos:
