services:

   web:
    build: apache
    hostname: web
    ports:
      - 8000:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - prestashop.a23bernalrc.ddnsfree.com
          - www.prestashop.a23bernalrc.ddnsfree.com
    volumes:
      - ./app:/var/www/html
      - ./configs:/etc/apache2/sites-enabled
      - ./certs:/certs

networks:
  rede_test:
volumes:
  datos: