# Generated by Django 4.2.18 on 2025-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
