# Generated by Django 4.2.18 on 2025-02-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_comment_useremail_alter_comment_com_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userEmail',
            new_name='email',
        ),
    ]
