services:

  web:
    build: apache
    hostname: web
    ports:
      - 8000:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - prestashop.a23bernalrc.ddnsfree.com
          - www.prestashop.a23bernalrc.ddnsfree.com
    volumes:
      - ./app:/var/www/html
      - ./configs/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
      - ./certs:/certs

  basededatos:
    image: mariadb:latest
    volumes:
      - datos:/var/lib/mysql
    env_file:
      - mariadb.env
    secrets:
      - mariadb
    networks:
      - rede_test

  phpmyadmin:
    image: phpmyadmin
    networks:
      - rede_test
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=basededatos
      - PMA_PORT=3306

secrets:
  mariadb:
    file: mariadb.txt

networks:
  rede_test:
volumes:
  datos: