# Generated by Django 4.2.18 on 2025-02-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardGames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='game',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardGames.brand'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
