services:
  web:
    build: apache
    hostname: web
    ports:
      - 80:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - daw2425.ddnsfree.com
          - www.daw2425.ddnsfree.com
    volumes:
      - ./app:/app
      - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
      - ./apache/certs:/certs
  basededatos:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIODB_USER: example-user # Modo array de propiedades usa :
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: example-database
    networks:
      - rede_test
    volumes:
      - datos:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
    - rede_test
    ports: 
      - 8080:80
    environment:
      - PMA_HOST=basededatos # Modo lista usa =

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - rede_test
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_test:
volumes:
  datos:
