# Generated by Django 4.2.20 on 2025-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='media/')),
                ('slug', models.SlugField(unique=True)),
                ('catFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catFk', to='app.category')),
            ],
        ),
    ]
